# Assume pandoc-scholar is in the parent directory.
# Should usually be overwritten or configured via an environment variable.
PANDOC_SCHOLAR_PATH   ?= $(shell dirname $(PWD))
ARTICLE_FILE=article.md
include $(PANDOC_SCHOLAR_PATH)/Makefile
